### ISSUE TITLE
Store API key in ENV

### ISSUE THREAD

**Issue by estensen** [kaada/please-play#1]
Is this API key for all of Google's services? If so it's easy to exhaust your free tier. Hope it's not connected to your credit card.

I would generate a new API key and store it in an environment variable instead:

```
import os

API_KEY = os.environ['GOOGLE_API_KEY']
```

**Comment by kaada** [comment]
Yea, that's probably a good idea. Fix commited and key regenerated! Thanks for the heads-up!
